### ISSUE TITLE
Tracking issue for GLVF 1.0

### ISSUE THREAD

**Issue by Perksey** [Ultz/GLVF#1]
# API Progress
- [x] Core API
- [x] Controllable State
- [x] Controllable Size
- [x] Controllable UI
- [x] Controllable Title
- [x] Enhanced Debugging
- [x] Event Driven Pump
- [x] File Drop
- [x] Gamepad Input
- [x] Joystick Input
- [x] Keyboard Input
- [x] Mouse Input
- [x] Multiview Support
- [x] OpenGL support
- [x] Vulkan support
- [ ] Screen APIs

# Development
- [ ] [In Progress] GLVF emulation on desktop via GLFW
- [ ] [Not Started] iOS support
- [ ] [Not Started] Android support

# Milestones
- [ ] Preview 1 with Desktop emulation
- [ ] Preview 2 with iOS support
- [ ] Preview 3 with Android support
- [ ] Preview 4 bugfix and release candidate
- [ ] Full release :tada:

Full release will align with Silk.NET 2.0's full release.
